### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by ahmadibrahim964** [btuznik/porousGasificationFoam#2] opened 2022-06-01 13:08 UTC
When compiling this solver on OpenFOAM v8 I face numerous errors. I am using MacOS Mojave version 10.14.6 (2017). I will talk you through my procedure of compiling the solver:

I download porousGasificationFoam-master and copied the folder to my working space.
I open a terminal and launch openfoam v8 using openfoam8-macos.
I navigate to my RUN folder (folder which contains porousGasificationFoam-master) and then navigate to porousGasificationFoam-master.
I source OpenFOAM 8 using $ source /opt/openfoam8/etc/bashrc
I source porousGasificationFoamMediaDirectories using $ source porousGasificationMediaDirectories.
I type in ./Allwclean.
I type in ./Allwmake.
The compilation begins, however after a while I get the following errors:

In file included from pyrolysisModel/volPyrolysis/volPyrolysis.C:27:
pyrolysisModel/volPyrolysis/volPyrolysis.H:93:13: error: 'BasicSolidChemistryModel' was not declared in this scope; did you mean 'basicSolidChemistryModel'?
93 | autoPtr<BasicSolidChemistryModel> solidChemistry_;
| ^~~~~~~~~~~~~~~~~~~~~~~~
| basicSolidChemistryModel
pyrolysisModel/volPyrolysis/volPyrolysis.H:93:38: error: template argument 1 is invalid
93 | autoPtr<BasicSolidChemistryModel> solidChemistry_;
| ^~~~~~~~~~~~~~
pyrolysisModel/volPyrolysis/volPyrolysis.H:93:52: error: expected unqualified-id before '>' token
93 | autoPtr<BasicSolidChemistryModel> solidChemistry_;
| ^~
pyrolysisModel/volPyrolysis/volPyrolysis.C: In member function 'void Foam::heterogeneousPyrolysisModels::volPyrolysis::solveSpeciesMass()':
pyrolysisModel/volPyrolysis/volPyrolysis.C:113:37: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
113 | volScalarField sRhoSi = solidChemistry_->RRs(i);
| ^~~~~~~~~~~~~~~
| solidChemistrySh
pyrolysisModel/volPyrolysis/volPyrolysis.C: In member function 'void Foam::heterogeneousPyrolysisModels::volPyrolysis::calculateMassTransfer()':
pyrolysisModel/volPyrolysis/volPyrolysis.C:267:50: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
267 | totalGasMassFlux_ = fvc::domainIntegrate(solidChemistry_->RRg());
| ^~~~~~~~~~~~~~~
| solidChemistrySh
pyrolysisModel/volPyrolysis/volPyrolysis.C: In constructor 'Foam::heterogeneousPyrolysisModels::volPyrolysis::volPyrolysis(const Foam::word&, const Foam::fvMesh&, Foam::HGSSolidThermo&, Foam::psiReactionThermo&, Foam::volScalarField&)':
pyrolysisModel/volPyrolysis/volPyrolysis.C:319:5: error: class 'Foam::heterogeneousPyrolysisModels::volPyrolysis' does not have any field named 'solidChemistry_'
319 | solidChemistry_
| ^~~~~~~~~~~~~~~
pyrolysisModel/volPyrolysis/volPyrolysis.C:321:9: error: 'BasicSolidChemistryModel' was not declared in this scope; did you mean 'basicSolidChemistryModel'?
321 | BasicSolidChemistryModel::New
| ^~~~~~~~~~~~~~~~~~~~~~~~
| basicSolidChemistryModel
pyrolysisModel/volPyrolysis/volPyrolysis.C:321:48: error: expected primary-expression before '>' token
321 | BasicSolidChemistryModel::New
| ^
pyrolysisModel/volPyrolysis/volPyrolysis.C:326:9: error: no matching function for call to 'New(Foam::HGSSolidThermo&, Foam::PtrList<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> >&, Foam::word)'
326 | )
| ^

pyrolysisModel/volPyrolysis/volPyrolysis.C: In constructor 'Foam::heterogeneousPyrolysisModels::volPyrolysis::volPyrolysis(const Foam::word&, const Foam::fvMesh&, Foam::HGSSolidThermo&, Foam::psiReactionThermo&, Foam::volScalarField&, Foam::volScalarField&)':
pyrolysisModel/volPyrolysis/volPyrolysis.C:649:5: error: class 'Foam::heterogeneousPyrolysisModels::volPyrolysis' does not have any field named 'solidChemistry_'
649 | solidChemistry_
| ^~~~~~~~~~~~~~~
pyrolysisModel/volPyrolysis/volPyrolysis.C:651:9: error: 'BasicSolidChemistryModel' was not declared in this scope; did you mean 'basicSolidChemistryModel'?
651 | BasicSolidChemistryModel::New
| ^~~~~~~~~~~~~~~~~~~~~~~~
| basicSolidChemistryModel
pyrolysisModel/volPyrolysis/volPyrolysis.C:651:48: error: expected primary-expression before '>' token
651 | BasicSolidChemistryModel::New
| ^
pyrolysisModel/volPyrolysis/volPyrolysis.C:656:9: error: no matching function for call to 'New(Foam::HGSSolidThermo&, Foam::PtrList<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> >&, Foam::word)'
656 | )
| ^

pyrolysisModel/volPyrolysis/volPyrolysis.C: In member function 'virtual void Foam::heterogeneousPyrolysisModels::volPyrolysis::preEvolveRegion()':
pyrolysisModel/volPyrolysis/volPyrolysis.C:1002:13: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
1002 | solidChemistry_->setCellReacting(cellI, true);
| ^~~~~~~~~~~~~~~
| solidChemistrySh
pyrolysisModel/volPyrolysis/volPyrolysis.C:1006:13: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
1006 | solidChemistry_->setCellReacting(cellI, false);
| ^~~~~~~~~~~~~~~
| solidChemistrySh
pyrolysisModel/volPyrolysis/volPyrolysis.C: In member function 'virtual void Foam::heterogeneousPyrolysisModels::volPyrolysis::evolveRegion()':
pyrolysisModel/volPyrolysis/volPyrolysis.C:1025:17: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
1025 | timeChem_ = solidChemistry_->solve
| ^~~~~~~~~~~~~~~
| solidChemistrySh
pyrolysisModel/volPyrolysis/volPyrolysis.C: In member function 'virtual void Foam::heterogeneousPyrolysisModels::volPyrolysis::evolvePorosity()':
pyrolysisModel/volPyrolysis/volPyrolysis.C:1060:27: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
1060 | porositySource_ = solidChemistry_->RRpor(T_)();
| ^~~~~~~~~~~~~~~
| solidChemistrySh
pyrolysisModel/volPyrolysis/volPyrolysis.C: In member function 'virtual Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > Foam::heterogeneousPyrolysisModels::volPyrolysis::Srho() const':
pyrolysisModel/volPyrolysis/volPyrolysis.C:1165:40: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
1165 | const speciesTable& gasTable = solidChemistry_->gasTable();
| ^~~~~~~~~~~~~~~
| solidChemistrySh
pyrolysisModel/volPyrolysis/volPyrolysis.C: In member function 'virtual Foam::tmp<Foam::GeometricField<double, Foam::fvPatchField, Foam::volMesh> > Foam::heterogeneousPyrolysisModels::volPyrolysis::Srho(Foam::label) const':
pyrolysisModel/volPyrolysis/volPyrolysis.C:1182:40: error: 'solidChemistry_' was not declared in this scope; did you mean 'solidChemistrySh'?
1182 | const speciesTable& gasTable = solidChemistry_->gasTable();

Is there a way to fix this?

**Comment by btuznik** [comment] 2022-06-02 09:53
Hi,
I've just compiled a fresh copy of the repo and everything works fine. It seems that there must be some problem with your configuration. Can you please provide me with additional information?

- Is your of8 installed properly, are you able to run any of the cases from the tutorial directory?

**Comment by btuznik** [comment] 2022-06-02 09:58
Hi,
I've just compiled a fresh copy of the repo and everything works fine. It seems that there must be some problem with your configuration. Can you please provide me with additional information?

- Is your of8 installed properly, are you able to run any of the cases from the _$FOAM_TUTORIALS_ directory?
- What is the output of  `$ echo $FOAM_HGS` and `$ echo $WM_PROJECT_DIR` (please source the _porousGasificationMediaDirectories_ before executing these commands)

**Comment by ahmadibrahim964** [comment] 2022-06-02 10:02
Hi Bartosz,

Thank you for your email. It would seem I cannot run a case properly on op8 the simple cavityClipped tutorial. I am familiar with openfoam, but I really get confused about where everything is installed and all that :) 

Can you please direct me step by step on what I have to do?

If I run cavityClipped using icoFoam I get the following error:

FOAM FATAL ERROR: 
cannot find file "/home/openfoam/ahmadibrahim-8/tutorials/incompressible/icoFoam/cavity/cavityClipped/0.5/p »

I am looking forward to your response.

Thank you.

Best wishes,

Ahmad

**Comment by ahmadibrahim964** [comment] 2022-06-02 10:06
Hi bartosz, 

The output of echo $WM_PROJECT_DIR is /opt/openfoam8

However, when I type in echo $FOAM_HGS I do not get an output, or rather I get a blank output.

**Comment by ahmadibrahim964** [comment] 2022-06-02 10:12
Hi Bartosz, 

When I try to navigate to $FOAM_TUTORIALS and solve for example the cavity problem, when I type in blockMesh, I get the following:

FOAM FATAL ERROR: 
The parent directory does not allow write permission to the process,
or one of the directories in "/opt/openfoam8/tutorials/incompressible/icoFoam/cavity/cavity/constant/polyMesh" did not allow search (execute) permission.

There is probably something wrong with the configuration, but I do not know what?

**Comment by btuznik** [comment] 2022-06-02 10:16
First of all, I would make sure that everything is set up according to these instructions:

https://openfoam.org/download/8-macos/

There might've been a step that you missed during the installation of the of8

**Comment by ahmadibrahim964** [comment] 2022-06-02 10:21
Hi Bartosz, 

I am a familiar openfoam user as I have worked on OpenFOAM - v1912 before. I just wanted to ask, as I am going through the steps you mentioned in your comments, do I have to download docker again and Xquartz again, or manipulate something in their configuration to help support the launching of op8?

**Comment by ahmadibrahim964** [comment] 2022-06-02 10:28
Hi Bartosz, 

Ok I have just tested openfoam8-macos again by using the following procedures:

cd $FOAM_RUN
cp -r $FOAM_TUTORIALS/incompressible/simpleFoam/pitzDaily .
cd pitzDaily
blockMesh
simpleFoam

The simulation converged properly. Can you advise on what to do next?

**Comment by btuznik** [comment] 2022-06-02 10:31
Great, glad to hear it! So now please follow this steps. Open a new terminal and type:
`$ git clone https://github.com/btuznik/porousGasificationFoam.git`
`$ cd porousGasificationFoam/`
`$ source porousGasificationMediaDirectories`
`$ ./Allwmake`

**Comment by ahmadibrahim964** [comment] 2022-06-02 10:35
Hi Bartosz, 

I will post the output of ./Allwmake here so you can see what I get:

Ahmads-MacBook-Air:~ ahmadibrahim$ git clone https://github.com/btuznik/porousGasificationFoam.git
Cloning into 'porousGasificationFoam'...
remote: Enumerating objects: 2394, done.
remote: Total 2394 (delta 0), reused 0 (delta 0), pack-reused 2394
Receiving objects: 100% (2394/2394), 13.69 MiB | 216.00 KiB/s, done.
Resolving deltas: 100% (1531/1531), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/BasicSolidChemistryModel/BasicSolidChemistryModel.C'
  'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/basicSolidChemistryModel/basicSolidChemistryModel.C'
  'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/BasicSolidChemistryModel/BasicSolidChemistryModel.H'
  'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/basicSolidChemistryModel/basicSolidChemistryModel.H'
  'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/BasicSolidChemistryModel/BasicSolidChemistryModelI.H'
  'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/basicSolidChemistryModel/basicSolidChemistryModelI.H'
Ahmads-MacBook-Air:~ ahmadibrahim$ cd porousGasificationFoam/
Ahmads-MacBook-Air:porousGasificationFoam ahmadibrahim$ source porousGasificationMediaDirectories 
Ahmads-MacBook-Air:porousGasificationFoam ahmadibrahim$ ./Allwmake 
usage: mkdir [-pv] [-m mode] directory ...
cp: /applications/utilities/Allwclean: Permission denied
cp: /applications/utilities/Allwmake: Permission denied
cp: /applications/utilities/setPorosity: Permission denied
cp: utilities/setPorosity: unable to copy extended attributes to /applications/utilities/setPorosity: Permission denied
cp: /applications/utilities/setPorosity/setPorosity.C: No such file or directory
cp: /applications/utilities/setPorosity/medium.H: No such file or directory
cp: /applications/utilities/setPorosity/Make: No such file or directory
cp: utilities/setPorosity/Make: unable to copy extended attributes to /applications/utilities/setPorosity/Make: No such file or directory
cp: /applications/utilities/setPorosity/Make/options: No such file or directory
cp: /applications/utilities/setPorosity/Make/files: No such file or directory
cp: /applications/utilities/setPorosity/createFields.H: No such file or directory
cp: /applications/utilities/totalMassPorousGasificationFoam: Permission denied
cp: utilities/totalMassPorousGasificationFoam: unable to copy extended attributes to /applications/utilities/totalMassPorousGasificationFoam: Permission denied
cp: /applications/utilities/totalMassPorousGasificationFoam/README.md: No such file or directory
cp: /applications/utilities/totalMassPorousGasificationFoam/Make: No such file or directory
cp: utilities/totalMassPorousGasificationFoam/Make: unable to copy extended attributes to /applications/utilities/totalMassPorousGasificationFoam/Make: No such file or directory
cp: /applications/utilities/totalMassPorousGasificationFoam/Make/options: No such file or directory
cp: /applications/utilities/totalMassPorousGasificationFoam/Make/files: No such file or directory
cp: /applications/utilities/totalMassPorousGasificationFoam/createFields.H: No such file or directory
cp: /applications/utilities/totalMassPorousGasificationFoam/totalMassPorousGasificationFoam.C: No such file or directory
cp: /applications/utilities/totalMassPorousGasificationFoam/readFields.H: No such file or directory
./Allwmake: line 17: wmake: command not found
./Allwmake: line 20: wmake: command not found
+ wmake libso solid
./Allwmake: line 6: wmake: command not found
+ wmake libso HGSSolidThermo
./Allwmake: line 7: wmake: command not found
+ wmake libso solidChemistryModel
./Allwmake: line 8: wmake: command not found
./Allwmake: line 26: wmake: command not found
./Allwmake: line 29: wmake: command not found
./Allwmake: line 32: ./Allwmake: No such file or directory

Any advise why I get these errors?

**Comment by btuznik** [comment] 2022-06-02 10:42
> warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree:
> 
> 'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/BasicSolidChemistryModel/BasicSolidChemistryModel.C' 'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/basicSolidChemistryModel/basicSolidChemistryModel.C' 'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/BasicSolidChemistryModel/BasicSolidChemistryModel.H' 'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/basicSolidChemistryModel/basicSolidChemistryModel.H' 'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/BasicSolidChemistryModel/BasicSolidChemistryModelI.H' 'porousGasificationMedia/thermophysicalModels/solidChemistryModel/solidChemistryModel/basicSolidChemistryModel/basicSolidChemistryModelI.H'

It seems that you have a case-insensitive filesystem and that collides with our repo.  Step 5 in the instruction that I've mentioned addresses this issue:

https://openfoam.org/download/8-macos/

**Comment by ahmadibrahim964** [comment] 2022-06-02 10:44
Hi,

I will follow the step and get back to you :)

**Comment by ahmadibrahim964** [comment] 2022-06-02 11:31
Hi Bartosz, 

I followed step 5, but when I try writing $ git clone https://github.com/btuznik/porousGasificationFoam.git, I get the same warning as above "warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree..."

Am I missing something here?

**Comment by btuznik** [comment] 2022-06-02 12:45
Did you clone the repo inside the mounted directory? 
If not try:
`cd $HOME/openfoam`
`openfoam8-macos`

And clone the repo from somewehere inside this directory

**Comment by ahmadibrahim964** [comment] 2022-06-02 12:53
Hi Bartosz,

When I type in cd $HOME/OpenFOAM then openfoam8-macos, open foam is launched.

Then when I try cloning the repo by typing 
$ git clone https://github.com/btuznik/porousGasificationFoam.git

I get this:

bash: git: command not found

I believe I have to do this all over again so that I do not get confused, are you able to give a step by step procedure on how to:

1. create the case sensitive volume. 
2. mount the file system 
3. clone the repo in the mounted directory 

and so on ?

I tried creating the case sensitive file system using step 5 of the procedures (i.e.):

sudo curl -o /usr/local/bin/openfoam-macos-file-system http://dl.openfoam.org/docker/openfoam-macos-file-system
sudo chmod 755 /usr/local/bin/openfoam-macos-file-system

after this, I launched OpenFOAM using:

cd $HOME/OpenFOAM
openfoam8-macos

here, when I try cloning using:

$ git clone https://github.com/btuznik/porousGasificationFoam.git

I get:

bash: git: command not found

**Comment by btuznik** [comment] 2022-06-02 13:03
Ok, it seems that there is no git installed in the docker image. So try this:
`$cd $HOME/openfoam`
`$ git clone https://github.com/btuznik/porousGasificationFoam.git`
`openfoam8-macos`

In that way, you will be inside the directory with proper file system, and would be able to clone the repo from outside your docker image.

**Comment by ahmadibrahim964** [comment] 2022-06-02 13:11
Hi,

I tried what you said, and I still get the same warning:

"warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree:" :)

I think if you let me know the step by step procedure of creating the case sensitive file system up until installing porousgasificationFoam, I would be able to do it. I believe there are steps that I am missing. Please excuse me as I am not familiar with the whole programming procedures, which is why I am getting confused.

**Comment by btuznik** [comment] 2022-06-02 14:03
Hi,

> I tried creating the case sensitive file system using step 5 of the procedures (i.e.):
> 
> sudo curl -o /usr/local/bin/openfoam-macos-file-system http://dl.openfoam.org/docker/openfoam-macos-file-system sudo chmod 755 /usr/local/bin/openfoam-macos-file-system
> 
> after this, I launched OpenFOAM using:
> 
> cd $HOME/OpenFOAM openfoam8-macos

But did you actually execute this script? Because from your description it seems that you have only downloaded it and set executable permissions. If not then do the following:

1. Delete the _$HOME/openfoam_ directory.
2. `$ openfoam-macos-file-system`
3. `$ cd $HOME/openfoam`
4. Try to clone the repository.

The last thing that comes to my mind would be to install git from inside your docker image (after executing _openfoam8-macos_ command) and then try to clone the repo. I don't have any experience with MacOS nor do I have access to a machine with such OS at the moment. So I can't reproduce the issues that you have.
 
If nothing works I would suggest starting at the beginning of the installation instructions for of8 and carefully examining every step.

**Comment by ahmadibrahim964** [comment] 2022-06-02 14:55
HI Bartosz, 

The thing is, I cannot delete $HOME_openfoam directory as I have simulation done with OpenFOAM - v1912 on it. Therefore, what I did was I copied those simulations to a new directory I created which is called OpenFOAM -v1912 and deleted the old directory I had them on. would that work?

Also, once I did that, I opened a new terminal, wrote down:

sudo curl -o /usr/local/bin/openfoam-macos-file-system http://dl.openfoam.org/docker/openfoam-macos-file-system sudo chmod 755 /usr/local/bin/openfoam-macos-file-system

then I typed in: $ openfoam-macos-file-system

once I did this, this is what I get: 

Script requires 1 command, e.g. "openfoam-macos-file-system create"

Usage: openfoam-macos-file-system [OPTIONS] <command>

commands:
  create       Initialize case-sensitive volume (only needed first time)
  automount    Configure macOS to mount the volume automatically on restart
  mount        Attach the case-sensitive volume
  unmount      Detach the case-sensitive volume
  compact      Remove any uneeded reserved space in the volume
  delete       Delete the disk image

options:
  -d | -dir <dir>      mount directory, default "/Users/ahmadibrahim/<volume-name>"
  -h | -help           help
  -n | -no-run         do not create the "run" directory
  -s | -size <size>    size of volume in GB, default 10, minimum 2
  -v | -volume <name>  name of volume, default "openfoam"

Creates a volume (disk image) with a case-sensitive filing system on a
macOS formatted disk (with a case-insensitive filing system) for use with
the Docker builds of OpenFOAM for macOS: http://openfoam.org/version/macos

Commands exist to create, mount, unmount, delete and compact the volume, and
to mount it automatically when the machine starts up.

By default, the volume is named "openfoam" with size of 10GB, mounted at
"$HOME/openfoam", and includes a "run" directory corresponding to the
$FOAM_RUN environment variable in the Docker container.  There are options to
override all these defaults.

How would I continue from here?

**Comment by ahmadibrahim964** [comment] 2022-06-02 15:39
Hi Bartosz, 

I tried typing in : $ openfoam-macos-file-system create 

and I get the following: 

create
hdiutil: create failed - File exists

so my question is how can the case-sensitive file exist and still produce a warning saying 

"warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree"

**Comment by ahmadibrahim964** [comment] 2022-06-02 15:55
Hi Bartosz, 

Ok, I have managed to create the case-sensitive file and mount it in my workspace. it is by default called openfoam and has a run directory inside it. I have still not launched openfoam yet. 

Do I now go inside the file system, clone the git and then launch openfoam by using : $openfoam8-macos?

Or do I launch openfoam before cloning the git?

Thanks in advance

**Comment by ahmadibrahim964** [comment] 2022-06-02 16:12
Hi Bartosz, 

Update: I first went inside the case sensitive openfoam folder, after that I did the following:

1. cloned the repo using : git clone https://github.com/btuznik/porousGasificationFoam.git
2. launched openfoam using: $ openfoam8-macos
3. navigated to porousgasificationFoam using cd porousGasificationFoam
4. sourced the file using source porousGasificationFoamMediaDirectories
5. ./Allwmake 

the compiler worked now. However before ./Allwmake I tried ./Allwclean and it gave the following:

Permission denied.

However when I stopped this and rather than typing ./Allwclean then ./Allwmake I just typed in ./Allwmake and it worked.

Is there any reason for this? Will this produce trouble later on in simulations?

I tested the solver by using porousGasificationFoam -help and it generated this:

Usage: porousGasificationFoam [OPTIONS]
options:
  -case <dir>       specify alternate case directory, default is the cwd
  -fileHandler <handler>
                    override the fileHandler
  -hostRoots <(((host1 dir1) .. (hostN dirN))>
                    slave root directories (per host) for distributed running
  -libs <(lib1 .. libN)>
                    pre-load libraries
  -listFunctionObjects
                    List functionObjects
  -listFvOptions    List fvOptions
  -listMomentumTransportModels
                    List momentumTransportModels
  -listRegisteredSwitches
                    List switches registered for run-time modification
  -listScalarBCs    List scalar field boundary conditions (fvPatchField<scalar>)
  -listSwitches     List switches declared in libraries but not set in
                    etc/controlDict
  -listUnsetSwitches
                    List switches declared in libraries but not set in
                    etc/controlDict
  -listVectorBCs    List vector field boundary conditions (fvPatchField<vector>)
  -noFunctionObjects
                    do not execute functionObjects
  -parallel         run in parallel
  -postProcess      Execute functionObjects only
  -roots <(dir1 .. dirN)>
                    slave root directories for distributed running
  -srcDoc           display source code in browser
  -doc              display application documentation in browser
  -help             print the usage

Using: OpenFOAM-8 (see https://openfoam.org)
Build: 8-1c9b5879390b

Does this mean the solver compiled?

Do I need to worry about the permissions ./Allwclean denied?

Thanks

**Comment by btuznik** [comment] 2022-06-10 11:16
Sorry for the late delay. I'm glad that you were able to overcome the issues.

If `Allwmake` ended without any errors and you are able to run our solver then everything works fine. I will look into the `Allwclean` script though, but it doesn't affect the solver itself.

**Closed as completed by btuznik** 2022-06-10 11:16 UTC
